### PR TITLE
Added backlog of whiteboard after clarification

### PR DESCRIPTION
**Pull request by david-vloedman**

### CODE REVIEW

**Comment by natkiypie** [comment]
testing testing

**Comment by david-vloedman** [comment]
Commenting

**Comment by natkiypie** [comment]
@david-vloedman

**Comment by natkiypie** [comment]
Testing... Again

**Comment by david-vloedman** [comment]
Stop using my PR as your sounding board

**Comment by david-vloedman** [comment]
- [ x] Top-level README “Table of Contents” is updated
 - [ x] Feature tasks for this challenge are completed
 - [ x] Unit tests written and passing
     - [x ] “Happy Path” - Expected outcome
     - [ x] Expected failure
     - [ x] Edge Case (if applicable/obvious)
 - [ x] README for this challenge is complete
     - [x ] Summary, Description, Approach & Efficiency, Solution
     - [ x] Link to code
     - [ x] Picture of whiteboard

**Comment by natkiypie** [comment]
@david-vloedman Please include returns in your JSDocs. https://jsdoc.app/tags-returns.html

Also, please include link to your documentation in your README.md

**Comment by natkiypie** [comment]
Did you get this **☝️** ???

**Comment by david-vloedman** [comment]
Ya, should I use my resubmit for one with a readme?

**Pull request merged**
