### PR TITLE
Hash table and tests

### PR DESCRIPTION
**Pull request by david-vloedman**
[ x] Top-level README “Table of Contents” is updated

[ x] Feature tasks for this challenge are completed

[ x] Unit tests written and passing

[x ] “Happy Path” - Expected outcome
[ x] README for this challenge is complete

[x ] Summary, Description, Approach & Efficiency, Solution
[ x] Link to code
[ x] Picture of whiteboard

### CODE REVIEW

**Comment by natkiypie** [comment]
In README.md, need:
- links to PR
- Travis-CI
- Documentation

**Comment by natkiypie** [comment]
You may also want to complete your whiteboarding.

**Comment by natkiypie** [comment]
- still need JSDocs
- need to complete whiteboarding

**Comment by david-vloedman** [comment]
@natkiypie @doug97703 

Docs, whiteboard, etc for hash-table complete.

**Comment by david-vloedman** [comment]
@natkiypie @doug97703 

Docs, whiteboard, etc for hash-table complete.

**Comment by david-vloedman** [comment]
@natkiypie @doug97703 

Docs, whiteboard, etc for hash-table complete.

**Pull request merged**
